// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import rehypeExternalLinks from 'rehype-external-links';

// https://astro.build/config
export default defineConfig({
	site: 'https://docs.vaultcms.org',
	markdown: {
		rehypePlugins: [
			[rehypeExternalLinks, { target: '_blank', rel: ['noopener', 'noreferrer'] }],
		],
	},
	integrations: [
		starlight({
			title: 'Vault CMS',
			components: {
				// Render the agent-facing llms.txt directive at the very top of
				// <main>, immediately before the page H1, so the converted content
				// has it within the first ~50% of the document.
				PageTitle: './src/components/PageTitle.astro',
			},
			head: [
				{
					tag: 'meta',
					attrs: { property: 'og:image', content: '/assets/opengraph.png' },
				},
				{
					tag: 'meta',
					attrs: { name: 'twitter:image', content: '/assets/opengraph.png' },
				},
				{
					tag: 'script',
					content: `
						window.addEventListener('DOMContentLoaded', () => {
							const logoLink = document.querySelector('.header .title-wrapper a');
							if (logoLink) {
								logoLink.href = 'https://vaultcms.org/';
							}
						});
					`,
				},
			],
			/* 
			   Logo is handled via custom.css to prevent the "flashing" 
			   caused by Astro's image processing during navigation.
			*/
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/davidvkimball/vaultcms' }],
			customCss: [
				'./src/styles/custom.css',
			],
			sidebar: [
				// Every group maps to one directory under src/content/docs/ and is
				// autogenerated from it, so adding a page to a folder adds it to the
				// sidebar. Ordering inside a group comes from `sidebar.order` in each
				// page's frontmatter; without it Starlight sorts alphabetically.
				{ label: 'Get started', items: [{ autogenerate: { directory: 'get-started' } }] },
				{ label: 'Concepts', items: [{ autogenerate: { directory: 'concepts' } }] },
				{ label: 'Guides', items: [{ autogenerate: { directory: 'guides' } }] },
				{ label: 'Themes', items: [{ autogenerate: { directory: 'themes' } }] },
				{ label: 'Plugins', items: [{ autogenerate: { directory: 'plugins' } }] },
				{ label: 'Troubleshooting', items: [{ autogenerate: { directory: 'troubleshooting' } }] },
			],
		}),
	],
});
