// @ts-check
import { defineConfig, fontProviders } from 'astro/config';
import starlight from '@astrojs/starlight';
import rehypeExternalLinks from 'rehype-external-links';

// https://astro.build/config
export default defineConfig({
	site: 'https://docs.vaultcms.org',
	markdown: {
		rehypePlugins: [
			// House style: external links open in a new tab with no rel attribute.
			// rehype-external-links defaults rel to nofollow when it is omitted, so
			// the empty array is what keeps it off.
			[rehypeExternalLinks, { target: '_blank', rel: [] }],
		],
	},
	// DM Sans is downloaded at build time and served from the site itself,
	// rather than @imported from Google Fonts on every page view. Body text is
	// the only place it is used (headings and code are monospace), so only the
	// weights Starlight's body styles reach are requested.
	fonts: [
		{
			provider: fontProviders.google(),
			name: 'DM Sans',
			cssVariable: '--font-dm-sans',
			weights: [400, 600, 700],
			styles: ['normal', 'italic'],
			subsets: ['latin'],
			fallbacks: ['system-ui', 'sans-serif'],
		},
	],
	integrations: [
		starlight({
			title: 'Vault CMS',
			components: {
				// Render the agent-facing llms.txt directive at the very top of
				// <main>, immediately before the page H1, so the converted content
				// has it within the first ~50% of the document.
				PageTitle: './src/components/PageTitle.astro',
				// Adds the self-hosted DM Sans @font-face rules and preload link.
				Head: './src/components/Head.astro',
			},
			head: [
				{
					tag: 'meta',
					attrs: { property: 'og:image', content: '/assets/opengraph.png' },
				},
				{
					tag: 'meta',
					attrs: { name: 'twitter:image', content: '/assets/opengraph.png' },
				},
				{
					tag: 'script',
					content: `
						window.addEventListener('DOMContentLoaded', () => {
							const logoLink = document.querySelector('.header .title-wrapper a');
							if (logoLink) {
								logoLink.href = 'https://vaultcms.org/';
							}
						});
					`,
				},
			],
			/* 
			   Logo is handled via custom.css to prevent the "flashing" 
			   caused by Astro's image processing during navigation.
			*/
			social: [{ icon: 'github', label: 'GitHub', href: 'https://github.com/davidvkimball/vaultcms' }],
			customCss: [
				'./src/styles/custom.css',
			],
			sidebar: [
				// Every group maps to one directory under src/content/docs/ and is
				// autogenerated from it, so adding a page to a folder adds it to the
				// sidebar. Ordering inside a group comes from `sidebar.order` in each
				// page's frontmatter; without it Starlight sorts alphabetically.
				{ label: 'Get started', items: [{ autogenerate: { directory: 'get-started' } }] },
				{ label: 'Concepts', items: [{ autogenerate: { directory: 'concepts' } }] },
				{ label: 'Guides', items: [{ autogenerate: { directory: 'guides' } }] },
				{ label: 'Themes', items: [{ autogenerate: { directory: 'themes' } }] },
				{ label: 'Plugins', items: [{ autogenerate: { directory: 'plugins' } }] },
				{ label: 'Troubleshooting', items: [{ autogenerate: { directory: 'troubleshooting' } }] },
			],
		}),
	],
});
